#!/usr/bin/env python

import sys, os

# extend module search path for dev access and use
cwd = os.getcwd()
sys.path.insert(0, cwd)

from tsapp import handle

if __name__ == '__main__':
    args = [unicode(arg, 'UTF-8') for arg in sys.argv[1:]]
    handle(args)
